%YAML:1.0
---
kpDescriptorType: orb
KPNonMaximaSuppresion: 0
targetFocus: -1.
minKFConfidence: 6.0000002384185791e-01
maxNewPoints: 350
enableLoopClosure: 1
targetWidth: 1.
maxFeatures: 4000
nthreads_feature_detector: 2
nOctaveLevels: 8
scaleFactor: 1.2000000476837158e+00
runSequential: 0
detectMarkers: 1
forceInitializationFromMarkers: 0
aruco_allowOneFrameInitialization: 0
reLocalizationWithKeyPoints: 1
reLocalizationWithMarkers: 1
inPlaneMarkers: 0
saveImageInMap: 0
minBaseLine: 7.0000000298023224e-02
detectKeyPoints: 1
removeKeyPointsIntoMarkers: 1
minDescDistance: 3.4028234663852886e+38
baseline_medianDepth_ratio_min: 9.9999997764825821e-03
aruco_markerSize: 0.177
projDistThr: 15
maxVisibleFramesPerMarker: 10
minNumProjPoints: 3
keyFrameCullingPercentage: 8.0000001192092896e-01
thRefRatio: 8.9999997615814209e-01
aruco_minerrratio_valid: 3.
aruco_minNumFramesRequired: 3
markersOptWeight: 5.0000000000000000e-01
minMarkersForMaxWeight: 5
autoAdjustKpSensitivity: 0
global_optimizer: g2o
aruco-dictionary: ARUCO_MIP_36h12 
aruco-detectMode: DM_NORMAL
aruco-cornerRefinementM: CORNER_SUBPIX
aruco-minSize: 0.
extraParams: ""
