pose_estimation:
  detector_offset: [0.05, 0, 0, rad(-pi/2), 0, rad(-pi/2)]
  markers:
    visual_marker_in_world_0: [1.80, 0, 0.65, rad(pi/2), rad(pi), -rad(pi)]
    #visual_marker_in_world_1: [0, -0.5, 0.3, rad(pi), rad(pi), 0]
    #visual_marker_in_world_2: [0, -0.5, 0.3, rad(pi), rad(pi), 0]
    #visual_marker_in_world_3: [0, -0.5, 0.3, rad(pi), rad(pi), 0]
    #visual_marker_in_world_4: [0, -0.5, 0.3, rad(pi), rad(pi), 0]
